packages:
  - playgrounds/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.2.4
  '@tanstack/react-query': ^5.100.8
  '@tanstack/react-router': ^1.169.1
  ky: ^2.0.2
  msw: ^2.14.2
  openapi-msw: ^2.0.0
  openapi-typescript: ^7.13.0
  react: ^19.2.5
  react-dom: ^19.2.5
  storybook: ^8.5.0
  tailwindcss: ^4.2.4
  vite-plugin-checker: ^0.9.3
  vitest: ^4.1.5

onlyBuiltDependencies:
  - esbuild
  - msw
