/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/travel-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List received travel expense requests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Travel expense requests awaiting the approver */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelRequest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one travel expense request with its expense breakdown */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TravelRequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The travel expense request detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelRequestDetail"];
                    };
                };
                /** @description No travel expense request with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve the request and route it to the next superior */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TravelRequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveInput"];
                };
            };
            responses: {
                /** @description The updated request (completed once it holds two approvals) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelRequestDetail"];
                    };
                };
                /** @description No travel expense request with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/travel-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject the request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TravelRequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The updated request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelRequestDetail"];
                    };
                };
                /** @description No travel expense request with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/superiors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List superiors selectable as the next approver */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Superiors whose judgment can be requested next */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Superior"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TravelRequestStatus: "pending" | "completed" | "rejected";
        TravelRequest: {
            id: string;
            purpose: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @description Total requested amount in JPY */
            totalAmount: number;
            status: components["schemas"]["TravelRequestStatus"];
            /** @description Approvals received so far; the request completes at 2 */
            approvalCount: number;
        };
        TravelRequestDetail: components["schemas"]["TravelRequest"] & {
            items: components["schemas"]["ExpenseItem"][];
        };
        ExpenseItem: {
            id: string;
            label: string;
            /** @description Item amount in JPY */
            amount: number;
        };
        ApproveInput: {
            /** @description The superior whose judgment is requested next */
            superiorId: string;
        };
        Superior: {
            id: string;
            name: string;
            title: string;
        };
    };
    responses: never;
    parameters: {
        TravelRequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
