/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents, filtered / sorted / paginated */
        get: {
            parameters: {
                query?: {
                    /** @description Repeatable. Omitted means every status. */
                    status?: components["schemas"]["IncidentStatus"][];
                    /** @description Single choice. Omitted means every severity. */
                    severity?: components["schemas"]["IncidentSeverity"];
                    /** @description User id. Omitted means every assignee, unassigned included. */
                    assignee?: string;
                    /** @description Signed sort key — a leading "-" means descending. */
                    sort?: components["schemas"]["IncidentSort"];
                    /** @description 1-based page number. */
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of incidents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one incident */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    incidentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentDetail"];
                    };
                };
                /** @description No such incident */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incidentId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an incident's comments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    incidentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The comments, oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
                /** @description No such incident */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the users an incident can be assigned to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every assignable user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        IncidentStatus: "open" | "acknowledged" | "resolved";
        /** @enum {string} */
        IncidentSeverity: "low" | "medium" | "high" | "critical";
        /** @enum {string} */
        IncidentSort: "openedAt" | "-openedAt" | "severity" | "-severity";
        User: {
            id: string;
            name: string;
        };
        IncidentSummary: {
            id: string;
            /** @description Human-facing identifier, e.g. INC-1043. */
            key: string;
            title: string;
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["IncidentSeverity"];
            /** @description null when nobody has picked the incident up. */
            assignee: components["schemas"]["User"] | null;
            /** Format: date-time */
            openedAt: string;
        };
        IncidentDetail: {
            id: string;
            key: string;
            title: string;
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["IncidentSeverity"];
            assignee: components["schemas"]["User"] | null;
            /** Format: date-time */
            openedAt: string;
            description: string;
            timeline: components["schemas"]["TimelineEvent"][];
        };
        TimelineEvent: {
            id: string;
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "opened" | "acknowledged" | "resolved" | "note";
            actor: string;
            message: string;
        };
        Comment: {
            id: string;
            author: string;
            body: string;
            /** Format: date-time */
            postedAt: string;
        };
        IncidentPage: {
            items: components["schemas"]["IncidentSummary"][];
            page: number;
            perPage: number;
            total: number;
            totalPages: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
