/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reading-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved reading items (filtered, sorted, paginated) */
        get: operations["getReadingItems"];
        put?: never;
        /** Register a URL. The server fills in a placeholder title and thumbnail. */
        post: operations["createReadingItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single reading item with its note */
        get: operations["getReadingItem"];
        put?: never;
        post?: never;
        /** Delete a reading item. Items marked "read" cannot be deleted. */
        delete: operations["deleteReadingItem"];
        options?: never;
        head?: never;
        /** Update the note and/or status of a reading item */
        patch: operations["updateReadingItem"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ReadingStatus: "unread" | "reading" | "read";
        /** @enum {string} */
        ReadingOrder: "asc" | "desc";
        /** @description List-view projection of a reading item (no note). */
        ReadingItemSummary: {
            id: string;
            url: string;
            title: string;
            thumbnailUrl: string;
            status: components["schemas"]["ReadingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Full reading item including the note (detail view). */
        ReadingItem: {
            id: string;
            url: string;
            title: string;
            thumbnailUrl: string;
            status: components["schemas"]["ReadingStatus"];
            /** Format: date-time */
            createdAt: string;
            note: string;
        };
        ReadingItemPage: {
            items: components["schemas"]["ReadingItemSummary"][];
            /** @description Total number of items matching the filter (across all pages). */
            total: number;
            page: number;
            perPage: number;
        };
        CreateReadingItemInput: {
            url: string;
        };
        /** @description Partial update; supply note, status, or both. */
        UpdateReadingItemInput: {
            note?: string;
            status?: components["schemas"]["ReadingStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getReadingItems: {
        parameters: {
            query?: {
                /** @description Filter by reading status. Omit for all statuses. */
                status?: components["schemas"]["ReadingStatus"];
                /** @description Include items registered on or after this date (YYYY-MM-DD). */
                createdFrom?: string;
                /** @description Include items registered on or before this date (YYYY-MM-DD). */
                createdTo?: string;
                /** @description Sort direction by registration date. */
                order?: components["schemas"]["ReadingOrder"];
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. */
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of reading items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingItemPage"];
                };
            };
        };
    };
    createReadingItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReadingItemInput"];
            };
        };
        responses: {
            /** @description The created reading item */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingItem"];
                };
            };
        };
    };
    getReadingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reading item detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingItem"];
                };
            };
            /** @description Reading item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteReadingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reading item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The item is marked "read" and cannot be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateReadingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReadingItemInput"];
            };
        };
        responses: {
            /** @description The updated reading item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingItem"];
                };
            };
            /** @description Reading item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
