/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrders"];
        put?: never;
        post: operations["submitOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Crust: "hand-tossed" | "pan" | "thin-crispy" | "stuffed";
        /** @enum {string} */
        Size: "medium" | "large";
        /** @enum {string} */
        Topping: "pepperoni" | "sausage" | "bacon" | "chicken" | "ham" | "mushroom" | "onion" | "green-pepper" | "black-olive" | "jalapeno" | "extra-cheese" | "pineapple";
        /** @enum {string} */
        PizzaOrderMode: "whole" | "half";
        PizzaOrderInput: {
            crust: components["schemas"]["Crust"];
            size: components["schemas"]["Size"];
            mode: components["schemas"]["PizzaOrderMode"];
            toppings?: components["schemas"]["Topping"][];
            leftToppings?: components["schemas"]["Topping"][];
            rightToppings?: components["schemas"]["Topping"][];
        };
        PizzaOrderConfirmation: {
            orderId: string;
            totalPrice: number;
        };
        PizzaOrderRecord: {
            orderId: string;
            totalPrice: number;
            crust: components["schemas"]["Crust"];
            size: components["schemas"]["Size"];
            mode: components["schemas"]["PizzaOrderMode"];
            toppings?: components["schemas"]["Topping"][];
            leftToppings?: components["schemas"]["Topping"][];
            rightToppings?: components["schemas"]["Topping"][];
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PizzaOrderRecord"][];
                };
            };
        };
    };
    submitOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PizzaOrderInput"];
            };
        };
        responses: {
            /** @description Order confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PizzaOrderConfirmation"];
                };
            };
        };
    };
}
